### ISSUE TITLE
Arduino IDE 8.12 problem

### ISSUE THREAD

**Issue by W4KRL** [JVKran/Forced-BME280#2]
Jochem, thank you for developing this lightweight library for the BME280. I had difficulty installing the library on a D1 Mini with the ESP8266 core on IDE version 1.8.12. It said it needed other libraries but gave an error message "no protocol" when I tried installing it that way. When installed without the other libraries, compilation failed with an error related to AVR interrupts. I then installed the complete set for version 2.0.0. Again, there was a "no protocol" error but version 2.0.0 installed and worked. I tried to update to 2.1.0 but again got the no protocol error however it did update the BME driver. It throws this error:

Arduino: 1.8.12 (Windows 10), Board: "LOLIN(WEMOS) D1 R2 & mini, 80 MHz, Flash, Legacy (new can return nullptr), All SSL ciphers (most compatible), 4MB (FS:2MB OTA:~1019KB), v2 Lower Memory, Disabled, None, Only Sketch, 921600"

C:\Users\KarlB\Documents\Arduino\libraries\TinyWireM\USI_TWI_Master.cpp:22:27: fatal error: avr/interrupt.h: No such file or directory

#include <avr/interrupt.h>
^
compilation terminated.

exit status 1
Error compiling for board LOLIN(WEMOS) D1 R2 & mini.

Conclusions: 2.0.0 works, 2.1.0 has a problem, and Arduino IDE 1.8.12 does not like the library.

**Comment by JVKran** [comment]
Hey Karl, thanks for the heads up. I managed to reproduce the error. It turns out that this issue also is a documentation problem. In the test sketch it states that a macro has got to be commented out to compile for anything other than an ATtiny (with TinyWireM). After this was commented out in "Documents/Arduino/Libraries/Forced-BME280/src/forcedClimate.h" it compiled without errors. 

I'm going to change the documentation right away! Once again, thanks for pointing this out. If you encounter any more problems, feel free to open up an issue once again!
