### ISSUE TITLE
Double Digit precision is lost

### ISSUE THREAD

**Issue by LenirSantiago** [JVKran/Forced-BME280#5]
Hello, the latest version does not have double digit precsion any more. I took a  look at the .h file and you should divide the return values by 100.0 instead of just 100 as doing so causes it to return a decimal value (or a float with .00 decimals).

Also, regarding the MCUs that do not have floats, perhaps you can use a macro to detect a attiny, if so do not use floats. If it doesnt detect a atttiny, then use floats. for example:
#if defined(ARDUINO_AVR_ATTINY)
do stuff...
return value/100
#else
do stuff
return value/100.0
#endif

This way it will not increase the code that gets copiled and you get to have the best of both worlds.

**Comment by LenirSantiago** [comment]
correct macro to detect is __AVR_ATtiny85__

This can also help you use Wire or TinyWireM automatically without having to edit the libary .h files.
#ifdef __AVR_ATtiny85__
#include <TinyWireM.h>
#define WIRE TinyWireM

#else
#include <Wire.h>
#define WIRE Wire
#endif

**Comment by JVKran** [comment]
First of all, thank you very much for pointing this out! I'm very busy with school right now so mistakes are made very easily; as is the case with the floating point problem. That is fixed right now.

As with the floating point hardware; almost no microcontroller has this. Floating point calculations will always be a lot slower than integer based calculations. However, some microcontrollers are so fast that it's barely noticable. That's why I gave the user the choice to use integer or floating point functions. 

I see now that this has unfortunately resulted in a sketch size of 78% for the ATtiny85. That's unacceptable and not the goal of this library; these functions are now removed (resulting in a sketch size of 48%). However, the speed difference between floats and integers on an ATtiny is so large that they have to keep returning integers for my goal (a real time application). That's why I now indeed use your above mentioned macro to determine when to return an int32_t or a float.

Furthermore, these same macros are now used to determine wether to use _Wire.h_ or _TinyWireM.h_. When I wrote this library, I wouldn't have thought other people wanted to use this library too. For me it was fine to take a look at the header file to comment something, but I can see there are nicer and easier ways for the broader public.

Thank you very much for the heads up on the floating point problem and for the need of automatic platform detection. That's a great addition. The most recent version contains these improvements and is now visible in the master branch.
